import { Text } from "@chakra-ui/react";
import Head from "next/head";
import { useCookies } from "react-cookie";
import { useQuery } from "react-query";
import Layout from "../components/Layout";
import { getTodos } from "../utils/fetchApi";

export default function Home({ todos1 }) {
  const [cookies] = useCookies();
  const { data } = useQuery(["/todos/1"], getTodos, {
    refetchInterval: 10000,
    initialData: todos1,
  });

  console.log(cookies.userToken)
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Text>Home page</Text>
        <pre>
          <code>{JSON.stringify(data, null, 2)}</code>
        </pre>
      </Layout>
    </div>
  );
}

export const getStaticProps = async () => {
  const todos1 = await getTodos();
  return { props: { todos1: {...todos1, nama: "Yos Sularko"} } };
};
