import { useRouter } from "next/router";
import { Text, Button } from "@chakra-ui/react";
import Head from "next/head";
import { useCookies } from "react-cookie";
import { useQuery } from "react-query";
import Layout from "../components/Layout";
import { getTodos } from "../utils/fetchApi";

export default function Home({ todos1 }) {
  const [cookies, _, removeCookie] = useCookies();
  const { data } = useQuery(["/todos/1"], getTodos, {
    refetchInterval: 10000,
    initialData: todos1,
  });

  const router = useRouter();

  const handleLogout = () => {
    removeCookie("userToken");
    router.replace("/auth/login");
  };

  console.log(cookies.userToken);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Text>Home page</Text>
        <Button onClick={handleLogout}>Logout</Button>
        <pre>
          <code>{JSON.stringify(data, null, 2)}</code>
        </pre>
      </Layout>
    </div>
  );
}

export const getStaticProps = async () => {
  const todos1 = await getTodos();
  return { props: { todos1: { ...todos1, nama: "Yos Sularko" } } };
};
