import { useRouter } from "next/router";
import { Text, Button } from "@chakra-ui/react";
import Head from "next/head";
import { useCookies } from "react-cookie";
import { useQuery } from "react-query";
import Layout from "../components/Layout";
import { getPosts, getTodos, getUsers } from "../utils/fetchApi";

export default function Home({ todos1, posts, users }) {
  const [cookies, _, removeCookie] = useCookies();
  const { data, isSuccess } = useQuery(["/todos/1"], getTodos, {
    refetchInterval: 10000,
    initialData: todos1,
  });
  const { data: dataPosts, isSuccess: isSuccessPosts } = useQuery(
    ["/posts"],
    getPosts,
    {
      refetchInterval: 15000,
      initialData: posts,
    }
  );
  const { data: dataUsers, isSuccess: isSuccessUsers } = useQuery(
    ["/users"],
    getUsers,
    {
      refetchInterval: 12000,
      initialData: users,
    }
  );

  const router = useRouter();

  const handleLogout = () => {
    removeCookie("userToken");
    router.replace("/auth/login");
  };

  console.log(cookies.userToken);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Text>Home page</Text>
        <Button onClick={handleLogout}>Logout</Button>
        <Text>Todos</Text>
        {isSuccess && (
          <pre>
            <code>{JSON.stringify(data, null, 2)}</code>
          </pre>
        )}
        <Text>Posts</Text>
        {isSuccessPosts && (
          <pre>
            <code>{JSON.stringify(dataPosts[0], null, 2)}</code>
          </pre>
        )}
        <Text>Users</Text>
        {isSuccessUsers && (
          <pre>
            <code>{JSON.stringify(dataUsers[0], null, 2)}</code>
          </pre>
        )}
      </Layout>
    </div>
  );
}

export const getStaticProps = async () => {
  const todos1 = await getTodos();
  const posts = await getPosts();
  const users = await getUsers();
  return {
    props: { todos1: { ...todos1, nama: "Yos Sularko" }, posts, users },
  };
};
